In [14]:
import numpy as np
import pandas as pd

In [15]:
data = pd.read_csv('./data/Merged-Formatted-Indian-Names.csv')

In [16]:
data.head()

name gender
0          barjraj      m
1     ramdin verma      m
2  sharat chandran      m
3  birender mandal      m
4             amit      m

In [17]:

data.size

60970

In [18]:
data.columns

Index(['name', 'gender'], dtype='object')

In [19]:
data.dtypes

name      object
gender    object
dtype: object

In [20]:
data = data.dropna()

In [21]:
data = data.reset_index(drop=True)

In [22]:
data.size

60860

In [23]:
data[data['gender'] == 'm'].size

29642

In [24]:
data[data['gender'] == 'f'].size

30702

In [25]:
data[data['gender'] == 'u'].size

516

In [26]:
data_names = data

In [27]:
data_names.size

60860

## Unisex: 0; Female: 1; Male: 2

In [28]:
data_names['gender'].replace({'u': 0,'f': 1,'m': 2},inplace=True)

In [29]:
data_names['gender'].unique()

array([2, 1, 0], dtype=int64)

In [30]:
data_names.dtypes

name      object
gender     int64
dtype: object

In [31]:
name_data = data_names['name']
training_labels = data_names['gender']

In [32]:
name_data[name_data.isna()].size

0

In [33]:
from sklearn.feature_extraction.text import CountVectorizer

In [34]:
cv = CountVectorizer()
training_data = cv.fit_transform(name_data)

In [40]:
print(training_data.toarray()[0])

[0 0 0 ... 0 0 0]


In [41]:
from sklearn.model_selection import train_test_split
train_set, test_set, train_labels, test_labels = train_test_split(training_data, training_labels, random_state =42, test_size= 0.33)

In [42]:
print('Training Set: ', train_set.shape[0])
print('Test Set: ', test_set.shape[0])
print('Training Labels: ', train_labels.shape[0])
print('Test Labels: ', test_labels.shape[0])

Training Set:  20388
Test Set:  10042
Training Labels:  20388
Test Labels:  10042


In [43]:
from sklearn.tree import DecisionTreeClassifier

In [44]:
clf = DecisionTreeClassifier()
clf.fit(train_set, train_labels)

DecisionTreeClassifier()

## Training accuracy

In [47]:
clf.score(train_set,train_labels)*100


97.78300961349814

## Test accuracy

In [48]:
clf.score(test_set,test_labels)*100

88.60784704242182

## Prediction on new data

In [49]:
sample_name = ["arijit"]
vect = cv.transform(sample_name).toarray()

In [50]:
vect

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [51]:
clf.predict(vect)

array([1], dtype=int64)

In [52]:
def predictGender(a):
    test_name = [a]
    vector = cv.transform(test_name).toarray()
    if clf.predict(vector)[0] == 0:
        print("Unisex")
    elif clf.predict(vector)[0] == 1:
        print("Female")
    elif clf.predict(vector)[0] == 2:
        print("Male")
    else:
        print("Unknown")

In [53]:
predictGender("Soumya Dey")

Female


In [54]:
predictGender("Arundhati Roy")

Male


In [55]:
predictGender("Meghnad Saha")

Female


In [56]:
predictGender("Deepika Padukon")

Female


In [57]:
predictGender("Manmohan Singh")

Male


In [58]:
predictGender("Virat Kohli")

Female


In [59]:
predictGender("Arjun Rampal")

Male


In [60]:
predictGender("Purnendu Paul")

Male


In [61]:
predictGender("Anik Ghoshal")

Female
