In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('./data/Merged-Formatted-Indian-Names.csv')

In [3]:
data.head()

name gender
0          barjraj      m
1     ramdin verma      m
2  sharat chandran      m
3  birender mandal      m
4             amit      m

In [4]:

data.size

62418

In [5]:
data.columns

Index(['name', 'gender'], dtype='object')

In [6]:
firstnames = []
lastCharOfFirstNames = []
for name in data['name']:
    firstnames.append(name.split(" ")[0])
    lastCharOfFirstNames.append(name.split(" ")[0][-1])

In [7]:
data['name'] = firstnames

In [8]:
data = data.replace('[^a-zA-Z0-9 \n\.]', '', regex=True)

In [9]:
data.dtypes

name      object
gender    object
dtype: object

In [10]:
data = data.dropna()

In [11]:
data = data.reset_index(drop=True)

In [12]:
data.size

62418

In [13]:
data[data['gender'] == 'm'].size

31114

In [14]:
data[data['gender'] == 'f'].size

31304

In [15]:
data_names = data

In [16]:
data_names.size

62418

## Unisex: 0; Female: 1; Male: 2

In [17]:
data_names['gender'].replace({'f': 1,'m': 2},inplace=True)

In [18]:
data_names['gender'].unique()

array([2, 1], dtype=int64)

In [19]:
data_names.dtypes

name      object
gender     int64
dtype: object

In [20]:
name_data = data_names['name']
training_labels = data_names['gender']

In [21]:
name_data[name_data.isna()].size

0

In [22]:
from sklearn.feature_extraction.text import CountVectorizer

In [23]:
cv = CountVectorizer()
training_data = cv.fit_transform(name_data)

In [24]:
print(training_data.toarray()[0])

[0 0 0 ... 0 0 0]


In [25]:
from sklearn.model_selection import train_test_split
train_set, test_set, train_labels, test_labels = train_test_split(training_data, training_labels, random_state =42, test_size= 0.30)

In [26]:
print('Training Set: ', train_set.shape[0])
print('Test Set: ', test_set.shape[0])
print('Training Labels: ', train_labels.shape[0])
print('Test Labels: ', test_labels.shape[0])

Training Set:  21846
Test Set:  9363
Training Labels:  21846
Test Labels:  9363


In [27]:
from sklearn.tree import DecisionTreeClassifier

In [28]:
clf = DecisionTreeClassifier()
clf.fit(train_set, train_labels)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

## Training accuracy

In [29]:
clf.score(train_set,train_labels)*100

96.3471573743477

## Test accuracy

In [30]:
clf.score(test_set,test_labels)*100

85.52814268930898

## Prediction on new data

In [31]:
sample_name = ["arijit"]
vect = cv.transform(sample_name).toarray()

In [32]:
vect

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [33]:
clf.predict(vect)

array([1], dtype=int64)

In [45]:
def predictGender(a):
    test_name = [a]
    vector = cv.transform(test_name).toarray()
    prediction = clf.predict(vector)
    probability = clf.predict_proba(vector)
    if prediction[0] == 1:
        print("Female", probability*100)
    elif prediction[0] == 2:
        print("Male", probability*100)
    else:
        print("Unknown")

In [46]:
predictGender("soumya")

Male [[  0. 100.]]


In [47]:
predictGender("Arundhati")

Female [[56.70103093 43.29896907]]


In [48]:
predictGender("virat")

Male [[  0. 100.]]


In [50]:
predictGender("purnendu")

Female [[56.70103093 43.29896907]]


In [49]:
predictGender("anik")

Male [[  0. 100.]]


In [39]:
predictGender("subir")

Male


In [44]:
predictGender("veerappan")

Female
