In [29]:
import numpy as np
import pandas as pd

In [30]:
data = pd.read_csv('./data/Merged-Formatted-Indian-Names.csv')

In [31]:
data.head()

name gender
0          barjraj      m
1     ramdin verma      m
2  sharat chandran      m
3  birender mandal      m
4             amit      m

In [32]:

data.size

62418

In [33]:
data.columns

Index(['name', 'gender'], dtype='object')

In [34]:
data.dtypes

name      object
gender    object
dtype: object

In [35]:
data = data.dropna()

In [36]:
data = data.reset_index(drop=True)

In [37]:
data.size

62418

In [38]:
data[data['gender'] == 'm'].size

31114

In [39]:
data[data['gender'] == 'f'].size

31304

In [40]:
data[data['gender'] == 'u'].size

0

In [41]:
data_names = data

In [42]:
data_names.size

62418

## Unisex: 0; Female: 1; Male: 2

In [43]:
data_names['gender'].replace({'f': 1,'m': 2},inplace=True)

In [44]:
data_names['gender'].unique()

array([2, 1], dtype=int64)

In [45]:
data_names.dtypes

name      object
gender     int64
dtype: object

In [46]:
name_data = data_names['name']
training_labels = data_names['gender']

In [47]:
name_data[name_data.isna()].size

0

In [48]:
from sklearn.feature_extraction.text import CountVectorizer

In [49]:
cv = CountVectorizer()
training_data = cv.fit_transform(name_data)

In [50]:
print(training_data.toarray()[0])

[0 0 0 ... 0 0 0]


In [51]:
from sklearn.model_selection import train_test_split
train_set, test_set, train_labels, test_labels = train_test_split(training_data, training_labels, random_state =42, test_size= 0.30)

In [52]:
print('Training Set: ', train_set.shape[0])
print('Test Set: ', test_set.shape[0])
print('Training Labels: ', train_labels.shape[0])
print('Test Labels: ', test_labels.shape[0])

Training Set:  21846
Test Set:  9363
Training Labels:  21846
Test Labels:  9363


In [53]:
from sklearn.tree import DecisionTreeClassifier

In [54]:
clf = DecisionTreeClassifier()
clf.fit(train_set, train_labels)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

## Training accuracy

In [55]:
clf.score(train_set,train_labels)*100


98.61301840153804

## Test accuracy

In [56]:
clf.score(test_set,test_labels)*100

88.3584321264552

## Prediction on new data

In [49]:
sample_name = ["arijit"]
vect = cv.transform(sample_name).toarray()

In [50]:
vect

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [51]:
clf.predict(vect)

array([1], dtype=int64)

In [52]:
def predictGender(a):
    test_name = [a]
    vector = cv.transform(test_name).toarray()
    if clf.predict(vector)[0] == 0:
        print("Unisex")
    elif clf.predict(vector)[0] == 1:
        print("Female")
    elif clf.predict(vector)[0] == 2:
        print("Male")
    else:
        print("Unknown")

In [53]:
predictGender("Soumya Dey")

Female


In [54]:
predictGender("Arundhati Roy")

Male


In [55]:
predictGender("Meghnad Saha")

Female


In [56]:
predictGender("Deepika Padukon")

Female


In [57]:
predictGender("Manmohan Singh")

Male


In [58]:
predictGender("Virat Kohli")

Female


In [59]:
predictGender("Arjun Rampal")

Male


In [60]:
predictGender("Purnendu Paul")

Male


In [61]:
predictGender("Anik Ghoshal")

Female
